# Commands may be slower in restricted environments, e.g. containers
command_timeout = 10000

format ="""
[ 󰄛 ](bold fg:#F8FAFC)\
$directory\
$fill\
$aws$kubernetes$git_branch$git_commit$git_state$git_status\
$docker_context$time
$character
"""

palette = 'main'
add_newline = true

[palettes.main]
c1 = '#C7FFD8' # blue light
c2 = '#002240' # blue dark
c3 = '#c6e7ff' # blue extra light
c4 = '#303030' # gray
c5 = '#808080' # gray light
c6 = '#C7FFD8' # green light


[fill]
symbol = " "

[character]
success_symbol = "[ ➜](fg:#5fa9f4)"
error_symbol = "[ ✖](fg:#FF204E)"


### Left prompt

[directory]
style = "fg:#5fa9f4 italic"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "fg:#15F5BA"
format = "[$symbol$branch]($style)"

[git_status]
stashed = "[*${count}](blue)"
modified = "[!${count}](fg:#FF204E)"
staged = "[+${count}](fg:#15F5BA)"
untracked = "[?${count}](fg:#5fa9f4)"
deleted = "[-${count}](fg:#5fa9f4)"
format = " ([$stashed$modified$staged$untracked $ahead_behind]($style))"
#format = " ([$all_status $ahead_behind]($style))"

[time]
disabled = false
format = '[ $time ](fg:#F8FAFC italic)'
time_format = '󰦖 %H:%M'


### Right prompt tools

[kubernetes]
disabled = false
format = '[󱃾 $context ](fg:#FFC7ED)'

[docker_context]
symbol = " "
format = "([  ](#767676)[$symbol$context]($style))"

[aws]
format = '[  $profile ](fg:#FF9F00)'
# Commands may be slower in restricted environments, e.g. containers
command_timeout = 10000

format ="""
[ 󰄛 ](bold fg:#F8FAFC)\
$directory\
$fill\
$aws$kubernetes$git_branch$git_commit$git_state$git_status\
$docker_context$time
$character
"""

palette = 'main'
add_newline = true

[palettes.main]
c1 = '#C7FFD8' # blue light
c2 = '#002240' # blue dark
c3 = '#c6e7ff' # blue extra light
c4 = '#303030' # gray
c5 = '#808080' # gray light
c6 = '#C7FFD8' # green light


[fill]
symbol = " "

[character]
success_symbol = "[ ➜](fg:#5fa9f4)"
error_symbol = "[ ✖](fg:#FF204E)"


### Left prompt

[directory]
style = "fg:#5fa9f4 italic"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "fg:#15F5BA"
format = "[$symbol$branch]($style)"

[git_status]
stashed = "[*${count}](blue)"
modified = "[!${count}](fg:#FF204E)"
staged = "[+${count}](fg:#15F5BA)"
untracked = "[?${count}](fg:#5fa9f4)"
deleted = "[-${count}](fg:#5fa9f4)"
format = " ([$stashed$modified$staged$untracked $ahead_behind]($style))"
#format = " ([$all_status $ahead_behind]($style))"

[time]
disabled = false
format = '[ $time ](fg:#F8FAFC italic)'
time_format = '󰦖 %H:%M'


### Right prompt tools

[kubernetes]
disabled = false
format = '[󱃾 $context ](fg:#FFC7ED)'

[docker_context]
symbol = " "
format = "([  ](#767676)[$symbol$context]($style))"

[aws]
format = '[  $profile ](fg:#FF9F00)'
