# ----------------------------------------------------- 
# Install packages 
# ----------------------------------------------------- 

installer_packages=(
    "hyprland"
    "waybar"
    "rofi-wayland"
    "dunst"
    "nautilus"
    "gnome-text-editor"
    "polkit-gnome"
    "pipewire"
    "xdg-desktop-portal"
    "xdg-desktop-portal-hyprland"
    "qt5-wayland"
    "qt6-wayland"
    "hyprpaper"
    "hyprlock"
    "hypridle"
    "noto-fonts"
    "papirus-icon-theme"
    "libnotify"
    "ttf-font-awesome"
    "neovim"
    "ttf-fira-sans" 
    "ttf-fira-code" 
    "ttf-firacode-nerd"
    "ttf-jetbrains-mono"
    "noto-fonts-emoji"
    "fuse2"
    "gtk4"
    "libadwaita"
    "jq"
    "python-gobject"
    "xdotool"
    "brightnessctl"
    "networkmanager"
    "wireplumber"
    "blueman"
    "bluez"
    "bluez-libs"
    "bluez-utils"
    "pavucontrol"
    "kitty"
    "flatpak"
    "bat"
    "eza"
    "fzf"
    "zsh"
    "starship"
    "swaync"
    "zsh-autosuggestions"
    "zsh-syntax-highlighting"
    "discord"
    "fd"
    "gnome-keyring"
    "bitwarden"
# DevOps tools
    "kubectl"
    "kubectx"
    "kubens"
    "k9s"
    "helm"
    "aws-cli"
)

installer_yay=(
    "wlogout" 
    "waypaper"
    "hyprshot"
    "zen-browser-bin"
    "spotify"
    "helmfile"
    "galaxybudsclient-bin"
    "anytype-bin"
    "bibata-cursor-theme-bin"
    "nautilus-open-any-terminal"
    "arsenal"
    "matugen-bin"
)

# PLEASE NOTE: Add more packages at the end of the following command
_installPackages "${installer_packages[@]}";
_installPackagesYay "${installer_yay[@]}";
